- name: Acte 2 - Configuration Interfaces csr1000
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false

  # Liste des tâches associées à notre Acte
  tasks:
      # configuration des interfaces
    - name: configuration interfaces
      cisco.ios.ios_l3_interfaces:
        config:
          - ipv4:
              - dhcp:
                  enable: true
            name: GigabitEthernet1

          - ipv4:
              - address: 192.168.2.1/24
            name: GigabitEthernet2

          - ipv4:
              - address: 192.168.3.1/24
            name: GigabitEthernet3
      
          - ipv4:
              - address: 192.168.4.1/24
            name: GigabitEthernet4
          
        state: merged


    - name: activation no shut sur les interfaces

      cisco.ios.ios_interfaces:
        # mise en place des interfaces en no shut
        config:
          - name: GigabitEthernet1
            description: "Interface en DHCP"
            enabled: true

          - name: GigabitEthernet2
            description: "Interface en IP statique"
            enabled: true

          - name: GigabitEthernet3
            description: "Interface en IP statique"
            enabled: true

          - name: GigabitEthernet4
            description: "Interface en IP statique"
            enabled: true
        state: merged

    - name: Supression du DHCP
      cisco.ios.ios_config:
        lines:
          - no ip dhcp pool SERVEUR

    - name: configuration DHCP
      cisco.ios.ios_config:
        lines:
          - ip dhcp pool SERVEUR
          - network 192.168.2.0 255.255.255.0
          - dns-server 8.8.8.8
          - default-router 192.168.2.1 255.255.255.0          
    
    - name: configuration NAT sortie
      cisco.ios.ios_config:
        lines:
          - ip nat outside
        parents: interface GigabitEthernet1

    - name: configuration NAT entrée
      cisco.ios.ios_config:
        lines:
          - int range GigabitEthernet2-4
          - ip nat inside

    - name: Activation du NAT
      cisco.ios.ios_config:
        lines:
          - access-list 1 permit 192.168.2.0 0.0.0.255
          - ip nat inside source list 1 interface GigabitEthernet1 overload


