- name: Acte 2 - Configuration Interfaces csr1000
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false

  # Liste des tâches associées à notre Acte
  tasks:
    - name: configuration interfaces
  cisco.ios.ios_l3_interfaces:
    config:
      - name: GigabitEthernet1
        ipv4:
          - dhcp: true

      - name: GigabitEthernet2
        ipv4:
          - address: 192.168.2.1/24

      - name: GigabitEthernet3
        ipv6:
          - address: 192.168.3.1/24
      
      - name: GigabitEthernet4
        ipv4:
          - address: 192.168.4.1/24
          
    state: merged