- name: Acte 2 - Configuration Interfaces csr1000
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false

  # Liste des tâches associées à notre Acte
  tasks:
      # configuration des interfaces
    - name: configuration interfaces
      cisco.ios.ios_l3_interfaces:
        config:
          - ipv4:
              - dhcp:
                  enable: true
            name: GigabitEthernet1

          - ipv4:
              - address: 192.168.2.1/24
            name: GigabitEthernet2

          - ipv4:
              - address: 192.168.3.1/24
            name: GigabitEthernet3
      
          - ipv4:
              - address: 192.168.4.1/24
            name: GigabitEthernet4
          
        state: merged


    - name: activation no shut sur les interfaces

      cisco.ios.ios_interfaces:
        # mise en place des interfaces en no shut
        config:
          - name: GigabitEthernet1
            description: "Interface en DHCP"
            enabled: true

          - name: GigabitEthernet2
            description: "Interface en IP statique"
            enabled: true

          - name: GigabitEthernet3
            description: "Interface en IP statique"
            enabled: true

          - name: GigabitEthernet4
            description: "Interface en IP statique"
            enabled: true
        state: merged
    